include missing <xmlrpc-c/string_int.h>
gives

| /tmp/xmlrpc-c/src/xmlrpc_libxml2.c: In function 'end_element':
| /tmp/xmlrpc-c/src/xmlrpc_libxml2.c:303:2: warning: implicit declaration of function 'xmlrpc_streq'
| ...
| ../src/libxmlrpc.so.3.25: undefined reference to `xmlrpc_streq'

else.